<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TemporarySite;
use Carbon\Carbon;

class TemporarySiteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sites = [
            [
                'temp_site_id' => 'TS001',
                'atoll_code' => 'AA',
                'site_name' => 'AA_Veligandu_Resort',
                'coverage' => '2G/3G/4G',
                'added_date' => '2023-12-06',
                'transmission_or_backhaul' => 'Rasdhoo – Veligandu link',
                'remarks' => 'Frequent power outages. Resort closed for renovation; completion date not confirmed',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS002',
                'atoll_code' => 'ADh',
                'site_name' => 'Adh_Holiday_Island_Resort',
                'coverage' => '2G/3G/4G',
                'added_date' => '2024-11-01',
                'transmission_or_backhaul' => 'HolidayIsland – Maamigili link',
                'remarks' => 'Closed for renovation. Frequent power outages and extended cell fiber cuts',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS003',
                'atoll_code' => 'B',
                'site_name' => 'B_Kihaadhuffaru_Resort',
                'coverage' => '3G/4G',
                'added_date' => '2025-09-13',
                'transmission_or_backhaul' => 'Kihaadhuffaru – Dharavandhoo link',
                'remarks' => 'Refer to email: Temp Site list Update (B_Kihaadhuffaru)',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS004',
                'atoll_code' => 'B',
                'site_name' => 'B_Maarikilu_Resort',
                'coverage' => '3G/4G',
                'added_date' => '2022-10-17',
                'transmission_or_backhaul' => 'Maarikilu – Kendhoo link',
                'remarks' => 'Agricultural island; no permanent power supply',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS005',
                'atoll_code' => 'B',
                'site_name' => 'B_Reethi_Beach_Resort',
                'coverage' => '2G/3G/4G',
                'added_date' => '2025-09-21',
                'transmission_or_backhaul' => 'ReethiBeach – Dharavandhoo link',
                'remarks' => 'Under construction; closed for renovation',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS006',
                'atoll_code' => 'Dh',
                'site_name' => 'Dh_Vaanee',
                'coverage' => '3G/4G',
                'added_date' => '2022-04-08',
                'transmission_or_backhaul' => 'Vaanee – Kudahuvadhoo link',
                'remarks' => 'Power issue expected to be resolved after 3 months; marked temporary',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS007',
                'atoll_code' => 'GDh',
                'site_name' => 'GDh_Konotta_Resort',
                'coverage' => '3G/4G',
                'added_date' => '2022-03-16',
                'transmission_or_backhaul' => 'Konotta – Madaveli link',
                'remarks' => 'Under construction',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS008',
                'atoll_code' => 'GDh',
                'site_name' => 'GDh_Maavarulu_Airport',
                'coverage' => '3G/4G',
                'added_date' => '2018-12-29',
                'transmission_or_backhaul' => 'Maavarulu – Kanduhulhudhoo link',
                'remarks' => 'Airport operational; temporary power connection',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS009',
                'atoll_code' => 'HDh',
                'site_name' => 'HDh_Hanimaadhoo_Airport',
                'coverage' => '2G/3G/4G',
                'added_date' => '2023-09-26',
                'transmission_or_backhaul' => 'Direct from Hanimaadhoo main site',
                'remarks' => 'Project period: Oct-2022 to Oct-2024',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS010',
                'atoll_code' => 'HDh',
                'site_name' => 'HDh_Hondaafushi_Resort',
                'coverage' => '2G/3G/4G',
                'added_date' => '2015-01-30',
                'transmission_or_backhaul' => 'Hondaafushi – Hanimaadhoo link',
                'remarks' => 'Under construction',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS011',
                'atoll_code' => 'K',
                'site_name' => 'K_Centara_Resort',
                'coverage' => '3G/4G',
                'added_date' => '2021-01-25',
                'transmission_or_backhaul' => 'Centara – Ihuru link',
                'remarks' => '21m, 3-leg temporary tower',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS012',
                'atoll_code' => 'K',
                'site_name' => 'K_Rihiveli_Resort',
                'coverage' => '2G/3G/4G',
                'added_date' => '2023-07-20',
                'transmission_or_backhaul' => 'Rihiveli – Fulidhoo link',
                'remarks' => 'Currently closed for renovation',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS013',
                'atoll_code' => 'K',
                'site_name' => 'K_2764_Ithaafushi_Private_Island',
                'coverage' => '3G/4G',
                'added_date' => '2019-09-08',
                'transmission_or_backhaul' => 'PrivateIsland – Ithaafushi link',
                'remarks' => 'No backup battery',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS014',
                'atoll_code' => 'K',
                'site_name' => 'K_2805_Ithaafushi_Resort2',
                'coverage' => '3G/4G',
                'added_date' => '2019-09-08',
                'transmission_or_backhaul' => 'Direct from Ithaafushi main site',
                'remarks' => 'No backup battery',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS015',
                'atoll_code' => 'K',
                'site_name' => 'K_Biyaadhoo_Resort',
                'coverage' => '3G/4G',
                'added_date' => '2025-06-17',
                'transmission_or_backhaul' => 'Biyaadhoo – Maafushi link',
                'remarks' => 'Closed for renovation',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS016',
                'atoll_code' => 'K',
                'site_name' => 'K_Bolidhuffaru_South_Resort',
                'coverage' => '3G/4G',
                'added_date' => '2025-08-22',
                'transmission_or_backhaul' => 'Bolidhuffaru South – BOH',
                'remarks' => 'Under construction',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS017',
                'atoll_code' => 'K',
                'site_name' => 'K_Dhonmaaga_Resort',
                'coverage' => '3G/4G',
                'added_date' => '2024-05-19',
                'transmission_or_backhaul' => 'Dhonmaaga – Maafushi link',
                'remarks' => 'Under construction',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS018',
                'atoll_code' => 'K',
                'site_name' => 'K_Emerald_Lagoon_Resort',
                'coverage' => '3G/4G',
                'added_date' => '2022-06-05',
                'transmission_or_backhaul' => 'Emerald Lagoon – Guraidhoo link',
                'remarks' => 'Under construction',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS019',
                'atoll_code' => 'K',
                'site_name' => 'K_Fun_Island_Resort',
                'coverage' => '2G/3G/4G',
                'added_date' => '2022-10-09',
                'transmission_or_backhaul' => 'Fun Island – Guraidhoo link',
                'remarks' => 'No longer operational',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS020',
                'atoll_code' => 'K',
                'site_name' => 'K_Gulhifalhu_AFCON',
                'coverage' => '3G/4G',
                'added_date' => '2024-12-15',
                'transmission_or_backhaul' => 'Gulhifalhu AFCONS – Viligili',
                'remarks' => 'Temporary contractor-built tower; possible LOS issues',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS021',
                'atoll_code' => 'K',
                'site_name' => 'K_Kudagiri',
                'coverage' => '3G/4G',
                'added_date' => '2023-06-07',
                'transmission_or_backhaul' => 'Kudagiri – Rasfushi link',
                'remarks' => 'Marked temporary until link issue is resolved',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS022',
                'atoll_code' => 'K',
                'site_name' => 'K_Maafushi_Prison',
                'coverage' => '3G/4G',
                'added_date' => '2022-03-29',
                'transmission_or_backhaul' => 'Direct from Maafushi main site',
                'remarks' => 'No backup battery',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS023',
                'atoll_code' => 'K',
                'site_name' => 'K_Maniyafaru_Resort',
                'coverage' => '3G/4G',
                'added_date' => '2019-04-24',
                'transmission_or_backhaul' => 'Maniyafaru – Emboodhoo Lagoon link',
                'remarks' => 'Under construction',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS024',
                'atoll_code' => 'K',
                'site_name' => 'K_Rosewood_Ranfaru_Resort',
                'coverage' => '3G/4G',
                'added_date' => '2024-08-12',
                'transmission_or_backhaul' => 'Maafushi – Ranfaru',
                'remarks' => 'Unstable electricity; backup generators planned',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS025',
                'atoll_code' => 'Lh',
                'site_name' => 'Lh_1443_Naifaru2',
                'coverage' => '3G/4G',
                'added_date' => '2019-10-22',
                'transmission_or_backhaul' => 'Direct from Naifaru main site',
                'remarks' => 'No backup battery',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS026',
                'atoll_code' => 'Lh',
                'site_name' => 'Lh_Innahuraa',
                'coverage' => '3G/4G',
                'added_date' => '2024-09-29',
                'transmission_or_backhaul' => 'Innahuraa – Olhuvelifushi',
                'remarks' => 'Under construction; closed for renovation',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS027',
                'atoll_code' => 'Lh',
                'site_name' => 'Lh_Komandoo_Resort',
                'coverage' => '2G/3G/4G',
                'added_date' => '2023-05-07',
                'transmission_or_backhaul' => 'Komandoo – Hinnavaru link',
                'remarks' => 'Closed for renovation; remove from temp list once reopened',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS028',
                'atoll_code' => 'Lh',
                'site_name' => 'Lh_Maafilaafushi',
                'coverage' => '2G/3G/4G',
                'added_date' => '2023-06-12',
                'transmission_or_backhaul' => 'Maafilaafushi – Kurendhoo link',
                'remarks' => 'Frequent power outages',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS029',
                'atoll_code' => 'Lh',
                'site_name' => 'Lh_Palm_Beach_Resort',
                'coverage' => '2G/3G/4G',
                'added_date' => '2022-05-12',
                'transmission_or_backhaul' => 'Palm Beach – Kurendhoo link',
                'remarks' => 'Under construction; closed for renovation',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS030',
                'atoll_code' => 'R',
                'site_name' => 'R_Fuggiri_Resort',
                'coverage' => '3G/4G',
                'added_date' => '2024-07-28',
                'transmission_or_backhaul' => 'Fuggiri – Hulhudhuffaaru link',
                'remarks' => 'Under construction',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS031',
                'atoll_code' => 'R',
                'site_name' => 'R_Kudakurath_Resort',
                'coverage' => '3G/4G',
                'added_date' => '2021-01-13',
                'transmission_or_backhaul' => 'Kudakurath – Rasmaadhoo link',
                'remarks' => 'Under construction',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS032',
                'atoll_code' => 'R',
                'site_name' => 'R_Maamigili_Resort',
                'coverage' => '2G/3G/4G',
                'added_date' => '2013-06-28',
                'transmission_or_backhaul' => 'Maamigili – Ungoofaaru link',
                'remarks' => 'Under construction',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS033',
                'atoll_code' => 'S',
                'site_name' => 'S_4421_Herathera_Resort_3G',
                'coverage' => '3G/4G',
                'added_date' => '2021-10-25',
                'transmission_or_backhaul' => 'Herathera1 – Hulhudhoo link',
                'remarks' => 'Under construction',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS034',
                'atoll_code' => 'S',
                'site_name' => 'S_4423_Herathera2_Resort_3G',
                'coverage' => '3G/4G',
                'added_date' => '2021-10-25',
                'transmission_or_backhaul' => 'Herathera2 – Hulhudhoo link',
                'remarks' => 'Under construction',
                'status' => 'Temporary',
            ],
            [
                'temp_site_id' => 'TS035',
                'atoll_code' => 'S',
                'site_name' => 'S_Viligili_Resort',
                'coverage' => '2G/3G/4G',
                'added_date' => '2021-04-08',
                'transmission_or_backhaul' => 'Viligili – Hulhudhoo link',
                'remarks' => 'Under construction',
                'status' => 'Temporary',
            ],
        ];

        foreach ($sites as $site) {
            TemporarySite::create($site);
        }

        $this->command->info('Successfully seeded 35 temporary sites.');
    }
}
