name: incident-management-system
services:
- name: web
  source_dir: /
  github:
    repo: Rannamaari/incident-management-system
    branch: main
    deploy_on_push: true
  run_command: heroku-php-apache2 public/
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: APP_NAME
    value: "Incident Management System"
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "true"
  - key: APP_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: APP_URL
    value: ${APP_URL}
  - key: LOG_CHANNEL
    value: stderr
  - key: LOG_STDERR_FORMATTER
    value: Monolog\Formatter\JsonFormatter
  - key: LOG_LEVEL
    value: debug
  - key: DB_CONNECTION
    value: mysql
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_PORT
    value: ${db.PORT}
  - key: DB_DATABASE
    value: ${db.DATABASE}
  - key: DB_USERNAME
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
  - key: CACHE_DRIVER
    value: array
  - key: SESSION_DRIVER
    value: cookie
  - key: SESSION_LIFETIME
    value: "120"
  - key: QUEUE_CONNECTION
    value: database
  - key: FILESYSTEM_DISK
    value: local
  - key: BROADCAST_DRIVER
    value: log

databases:
- name: db
  engine: MYSQL
  version: "8"
  num_nodes: 1
  size: db-s-dev-database

jobs:
- name: deploy
  source_dir: /
  github:
    repo: Rannamaari/incident-management-system
    branch: main
  environment_slug: php
  run_command: ./deploy-app.sh
  envs:
  - key: APP_ENV
    value: production
  - key: APP_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DB_CONNECTION
    value: mysql
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_PORT
    value: ${db.PORT}
  - key: DB_DATABASE
    value: ${db.DATABASE}
  - key: DB_USERNAME
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
  - key: CACHE_DRIVER
    value: array
  - key: SESSION_DRIVER
    value: cookie